// Account
export default {
    FETCH_LIST: 'ACCOUNT_FETCH_LIST',
    FETCH_LIST_SUCCESS: 'ACCOUNT_FETCH_LIST_SUCCESS',
    FETCH_LIST_FAILURE: 'ACCOUNT_FETCH_LIST_FAILURE',
    ACTION: 'ACCOUNT_ACTION',
    ACTION_FAILURE: 'ACCOUNT_ACTION_FAILURE',
};
