-- MySQL Script generated by MySQL Workbench
-- Mon Dec 11 08:40:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bmc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bmc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bmc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `bmc` ;

-- -----------------------------------------------------
-- Table `bmc_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `srvId` VARCHAR(16) NOT NULL COMMENT '业务服务ID',
  `type` INT NOT NULL COMMENT '类型',
  `name` VARCHAR(32) NOT NULL COMMENT '名称',
  `displayNameCN` VARCHAR(32) NOT NULL COMMENT '中文名称',
  `displayNameUS` VARCHAR(32) NOT NULL COMMENT '英文名称',
  `descriptionCN` VARCHAR(255) NULL COMMENT '中文描述',
  `descriptionUS` VARCHAR(255) NULL COMMENT '英文描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色';


-- -----------------------------------------------------
-- Table `bmc_account_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_account_role` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `accountId` BIGINT NULL COMMENT '帐号ID',
  `roleId` INT NULL COMMENT '角色ID',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '帐号角色关联';


-- -----------------------------------------------------
-- Table `bmc_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `srvId` VARCHAR(16) NOT NULL COMMENT '业务服务ID',
  `type` INT NULL COMMENT '类型',
  `name` VARCHAR(64) NOT NULL COMMENT '名称',
  `parentName` VARCHAR(64) NULL COMMENT '父名称',
  `displayNameCN` VARCHAR(50) NULL COMMENT '中文名称',
  `displayNameUS` VARCHAR(50) NULL COMMENT '英文名称',
  `isAuthz` BIT(1) NULL COMMENT '是否要认证',
  `descriptionCN` VARCHAR(255) NULL COMMENT '中文描述',
  `descriptionUS` VARCHAR(255) NULL COMMENT '英文描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '权限';


-- -----------------------------------------------------
-- Table `bmc_role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_role_permission` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `srvId` VARCHAR(16) NOT NULL COMMENT '业务服务ID',
  `permName` VARCHAR(64) NOT NULL COMMENT '权限名称',
  `roleName` VARCHAR(32) NOT NULL COMMENT '角色名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色权限关联';


-- -----------------------------------------------------
-- Table `bmc_history_pwd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_history_pwd` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `accountId` BIGINT NOT NULL COMMENT '帐号ID',
  `historyPwd` VARCHAR(128) NOT NULL COMMENT '历史密码',
  `modifyTime` DATETIME NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '历史密码';


-- -----------------------------------------------------
-- Table `bmc_system_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_system_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `srvId` VARCHAR(16) NOT NULL COMMENT '业务服务ID',
  `logLevel` VARCHAR(16) NULL COMMENT '日志级别',
  `source` VARCHAR(50) NULL COMMENT '来源',
  `baseInfo` VARCHAR(255) NULL COMMENT '基础信息',
  `result` INT NULL COMMENT '操作结果',
  `detail` VARCHAR(2048) NULL COMMENT '详细信息',
  `addInfo` VARCHAR(2048) NULL COMMENT '附件信息',
  `creationTime` DATETIME NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '系统日志';


-- -----------------------------------------------------
-- Table `bmc_security_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_security_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `srvId` VARCHAR(16) NOT NULL COMMENT '业务服务ID',
  `accountName` VARCHAR(32) NOT NULL COMMENT '帐号名称',
  `logLevel` VARCHAR(16) NULL COMMENT '日志级别',
  `operation` VARCHAR(50) NULL COMMENT '操作名称',
  `source` VARCHAR(50) NULL COMMENT '来源',
  `terminal` VARCHAR(50) NULL COMMENT '操作终端',
  `result` INT NULL COMMENT '操作结果',
  `detail` VARCHAR(2048) NULL COMMENT '详细信息',
  `addInfo` VARCHAR(2048) NULL COMMENT '附加信息',
  `creationTime` DATETIME NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '安全日志';


-- -----------------------------------------------------
-- Table `bmc_operation_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_operation_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `srvId` VARCHAR(16) NOT NULL COMMENT '业务服务ID',
  `accountName` VARCHAR(32) NOT NULL COMMENT '帐号名称',
  `logLevel` VARCHAR(16) NULL COMMENT '日志级别',
  `operation` VARCHAR(50) NULL COMMENT '操作名称',
  `source` VARCHAR(50) NULL COMMENT '来源',
  `terminal` VARCHAR(50) NULL COMMENT '操作终端',
  `result` INT NULL COMMENT '操作结果',
  `detail` VARCHAR(2048) NULL COMMENT '详细信息',
  `addInfo` VARCHAR(2048) NULL COMMENT '附加信息',
  `creationTime` DATETIME NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '操作日志';


-- -----------------------------------------------------
-- Table `bmc_idletimeout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_idletimeout` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `accountId` BIGINT NOT NULL COMMENT '帐号ID',
  `timeout` INT NOT NULL COMMENT '超时时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户闲时时间';


-- -----------------------------------------------------
-- Table `bmc_object_identity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_object_identity` (
  `name` VARCHAR(50) NOT NULL COMMENT '业务名称',
  `value_x` BIGINT NULL COMMENT '自增ID值',
  PRIMARY KEY (`name`))
ENGINE = InnoDB
COMMENT = '对象ID自增';


-- -----------------------------------------------------
-- Table `bmc_perm_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_perm_resource` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `srvId` VARCHAR(16) NULL COMMENT '业务服务ID',
  `permName` VARCHAR(64) NULL COMMENT '权限名称',
  `path` VARCHAR(128) NULL COMMENT '资源路径',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '权限资源';


-- -----------------------------------------------------
-- Table `bmc_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_account` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `srvId` VARCHAR(16) NOT NULL COMMENT '业务服务ID',
  `name` VARCHAR(20) NOT NULL COMMENT '帐号名称',
  `type` INT NULL DEFAULT 0 COMMENT '帐号类型',
  `password` VARCHAR(128) NULL COMMENT '密码',
  `salt` VARCHAR(32) NULL COMMENT '算法盐值',
  `status` INT UNSIGNED NULL DEFAULT 0 COMMENT '状态',
  `phoneNumber` VARCHAR(18) NULL COMMENT '手机号',
  `isFirstLogin` TINYINT(1) NULL COMMENT '是否第一次登录',
  `lockTime` DATETIME NULL COMMENT '锁定时间',
  `lastAccessTime` DATETIME NULL COMMENT '最后访问时间',
  `lastAccessIpAddr` VARCHAR(20) NULL COMMENT '最后访问IP地址',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '帐号';


-- -----------------------------------------------------
-- Table `bmc_api_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_api_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `srvId` VARCHAR(16) NOT NULL COMMENT '业务服务ID',
  `logLevel` VARCHAR(16) NULL COMMENT '日志级别',
  `operation` VARCHAR(50) NULL COMMENT '操作名称',
  `source` VARCHAR(50) NULL COMMENT '来源',
  `terminal` VARCHAR(50) NULL COMMENT '操作终端',
  `result` INT NULL COMMENT '操作结果',
  `detail` VARCHAR(2048) NULL COMMENT '详细信息',
  `addInfo` VARCHAR(2048) NULL COMMENT '附加信息',
  `creationTime` DATETIME NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'API接口';


-- -----------------------------------------------------
-- Table `bmc_dict_field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_dict_field` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `srv_id` VARCHAR(16) NOT NULL COMMENT '业务服务ID',
  `domain` VARCHAR(30) NOT NULL COMMENT '领域',
  `key_x` VARCHAR(30) NOT NULL COMMENT '关键字段',
  `value_x` VARCHAR(256) NULL COMMENT '数值',
  `utime` DATETIME NOT NULL COMMENT '更新时间',
  `ctime` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '数据字典';


-- -----------------------------------------------------
-- Table `bmc_dict_json`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bmc_dict_json` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `srv_id` VARCHAR(16) NOT NULL COMMENT '业务服务ID',
  `key_x` VARCHAR(30) NOT NULL COMMENT '关键字段',
  `value_x` TEXT NULL COMMENT '数值',
  `utime` DATETIME NOT NULL COMMENT '更新时间',
  `ctime` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '数据字典';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
